version: "3"

services:
  web:
    build: .
    container_name: web
    command: pipenv run python /code/src/run.py
    volumes:
      - .:/code
    ports:
      - 80:80
    tty: true
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: himitsu_lun_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"

volumes:
  dbdata: